networks:
  backend:

services:
  eegapi:
    image: registry.jakubkrawczyk.com/eeg/api
    build:
      context: .
      dockerfile: EegApi/Dockerfile
    ports:
      - 7999:8080
    networks:
      - backend
    depends_on:
      sql:
        condition: service_healthy
  sql:
    image: mariadb
    hostname: db.local
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: Eeg
    networks:
      - backend
    restart: on-failure
    volumes:
      - ./mariadb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 5s
      start_interval: 10s
      interval: 5s
      timeout: 5s
      retries: 3